config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check
  devise_for :users
  resources :categories 
  #, expect: [:show]
  resources :articles
  root "articles#index"
  
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    # Referenciando tabelas
    belongs_to :category
    belongs_to :user

    validates :title, presence: true, length: { minimum: 5 }
    validates :body, presence: true, length: { minimum: 10 }

    scope :desc_order, -> { order(created_at: :desc) }
    scope :without_highlights, ->(ids) { where("id NOT IN(#{ids})") if ids.present? }

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles, dependent: :restrict_with_error
    validates :name, presence: true, length: { minimum: 3 }
    scope :sorted, -> {order(:name)}
end

app/models/user.rb
class User < ApplicationRecord
  #se apagr o usuarios consequentemente ira apagar seu artigos
  has_many :articles, dependent: :destroy
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable,  and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :trackable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @highights = Article.desc_order.first(3)
    highights_ids = @highights.pluck(:id).join(',')
    @pagy, @articles = pagy(Article.desc_order.without_highlights(highights_ids))
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.sorted
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  
  def destroy
    if @category.destroy
      respond_to do |format|
        format.html { redirect_to categories_url, notice: t('app.destroy.success', model: Category.model_name.human) }
        format.json { head :no_content }
      end
    else
      redirect_to categories_url, alert: @category.errors.messages[:base][0]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
    def render_if(condition, template, record)
        render template, record if condition
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
    def date(datetime)
        datetime.strftime('%B %e, %Y')
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_about.html.erb
<div class="p-4 mb-3 bg-body-tertiary rounded">
    <h4 class="fst-italic">About</h4>
    <p class="mb-0">Customize this section to tell your visitors a little bit about your publication, writers, content, or something else entirely. Totally up to you.</p>
</div>

app/views/articles/_archives.html.erb
<div class="p-4">
    <h4 class="fst-italic">Archives</h4>
    <ol class="list-unstyled mb-0">
        <li><a href="#">March 2021</a></li>
        <li><a href="#">February 2021</a></li>
        <li><a href="#">January 2021</a></li>
        <li><a href="#">December 2020</a></li>
        <li><a href="#">November 2020</a></li>
        <li><a href="#">October 2020</a></li>
        <li><a href="#">September 2020</a></li>
        <li><a href="#">August 2020</a></li>
        <li><a href="#">July 2020</a></li>
        <li><a href="#">June 2020</a></li>
        <li><a href="#">May 2020</a></li>
        <li><a href="#">April 2020</a></li>
    </ol>
</div>

app/views/articles/_article.html.erb
 <br>
 <article class="blog-post">
    <h2 class="display-5 link-body-emphasis mb-1"><%= article.title%></h2>
    <p class="blog-post-meta">
        <%= render 'article_detail', article: article %>
    </p>
    <%# Truncate e usado para reduzir o texto e deixar de uma foto mais... %>
    <p> <%= link_to 'Continue reading ...', article, class: 'btn btn-link' %> </p>
    <p><%= truncate(article.body, length: 100) %></p>
    <div style="display: inline-block; margin-top: 30px">
    <%= link_to 'Edit  ', edit_article_path(article), class: 'btn btn-primary' %>
    </div>
    <div style="display: inline-block; margin-top: 30px">
		<%= button_to 'Destroy', article_path(article),
        method: :delete,
        data: { "turbo-confirm": 'Are you Sure?'}, class:'btn btn-danger'%>
    </div>
    <p>
</article>

app/views/articles/_article_detail.html.erb
<%= date(article.created_at)%> by <%= article.user.email%> in
<%= article.category.name%>

app/views/articles/_elsewhere.html.erb
<div class="p-4">
    <h4 class="fst-italic">Elsewhere</h4>
        <ol class="list-unstyled">
            <li><a href="#">GitHub</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Facebook</a></li>
        </ol>
</div>
     

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body, input_html: {rows: 12 } %>
    <%= f.association :category, collection: Category.sorted, prompt: "Choose a Category"%>
    

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary', id: 'liveAlertPlaceholder' %>
    <%= link_to 'Back', root_path, class: 'btn btn-secondary'%>
  </div>
<% end %>

app/views/articles/_longer_featured.html.erb
<div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
    <div class="col-lg-6 px-0">
      <h1 class="display-4 fst-italic"><%= article.title%></h1>
      <p class="lead my-3"><%= truncate(article.body, length: 100)%></p>
      <p class="lead mb-0">
        <%= link_to 'Continue reading...', article, class: 'text-body-emphasis fw-bold'%>
      </p>
    </div>
</div>

app/views/articles/_medium_featured.html.erb
<div class="col-md-6">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
          <strong class="d-inline-block mb-2 text-primary-emphasis"><%= article.category.name %></strong>
          <h3 class="mb-0"><%= article.title %> </h3>
          <div class="mb-1 text-body-secondary"> <%= render 'article_detail', article: article %> </div>
          <p class="card-text mb-auto"><%= truncate(article.body, length: 100)%></p>
          <a href="#" class="icon-link gap-1 icon-link-hover stretched-link">
            <%= link_to 'Continue reading...', article, class: 'icon-link gap-1 icon-link-hover stretched-link'%>
          </a>
        </div>
        <div class="col-auto d-none d-lg-block">
          <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        </div>
    </div>
</div>

app/views/articles/_pagination.html.erb
<br>
<div class="mb-4">
  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/articles/_right_side.html.erb
<div class="col-md-4">
    <div class="position-sticky" style="top: 2rem;">
        <%= render 'about' %>
        <%= render 'archives' %>   
        <%= render 'elsewhere'%>
    </div>
</div>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<ul class="dropdown-menu">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
  </ul>
</div>
<%# Artigo Grande  Principal%>
<%= render_if @highights[0].present?, 'longer_featured', article: @highights[0] %>
<%# Colunas div row 2 %>
<div class="row mb-2">
<%# Artigo Medio Secundario%>
<%= render_if @highights[1].present?, 'medium_featured', article: @highights[1]%>
<%= render_if @highights[2].present?, 'medium_featured', article: @highights[2]%>
</div>
<div class="row g-5">
    <div class="col-md-8">
      <h3 class="pb-4 mb-4 fst-italic border-bottom">
        From the Firehose
      </h3>


      <%= link_to 'New Article', new_article_path, class:'btn btn-success' %>
        <%= render @articles%>
        <%= render 'pagination'%>
    </div>
      <%= render 'right_side'%>
    </div>
    <%= content_for :category_filter  do %>
      <div class="nav-scroller py-1 mb-3 border-bottom">
        <nav class="nav nav-underline justify-content-between">
          <a class="nav-item nav-link link-body-emphasis active" href="#">World</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">U.S.</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Technology</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Design</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Culture</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Business</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Politics</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Opinion</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Science</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Health</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Style</a>
          <a class="nav-item nav-link link-body-emphasis" href="#">Travel</a>
        </nav>
    </div>
   <%end %>

   

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

app/views/articles/show.html.erb
<article class="blog-post">
    <h2 class="display-5 link-body-emphasis mb-1"><%= @article.title%></h2>
    <p class="blog-post-meta">
        <%= render 'article_detail', article:  @article %>
    </p>
    <p><%= @article.body %></p>
    <div style="display: inline-block; margin-top: 30px">
    <%= link_to 'Edit  ', edit_article_path(@article), class: 'btn btn-secondary' %>
    </div>
    <div style="display: inline-block; margin-top: 30px">
		<%= button_to 'Destroy', article_path(@article),
        method: :delete,
        data: { "turbo-confirm": 'Are you Sure?'}, class:'btn btn-danger'%>
    </div>
    <div style="display: inline-block; margin-top: 30px">
    <%= link_to 'Back', root_path, class: 'btn btn-secondary'%>
    </div>
    <p>
</article>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary', id: 'liveAlertPlaceholder' %>
    <%= link_to 'Back', categories_path, class: 'btn btn-secondary'%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<%= link_to "New category", new_category_path, class:'btn btn-success'%>
<br><br>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>

  <% @categories.each do |category| %>

  <tr>
      <td><%= category.name %> </td>
      <td>
        <div style="display: inline-block">
          <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-primary' %>
        </div>
            <div style="display: inline-block">
            <%= button_to 'Destroy', category, method: :delete,
            data: { "turbo-confirm": 'Are you Sure?'}, class:'btn btn-danger'%>
        </div>
      </td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/_account_links.html.erb
<% if user_signed_in?%>

<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    <%= current_user.email %>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to 'Edit User', edit_user_registration_path, class: 'dropdown-item'%></li>
    <li><hr class="dropdown-divider"></li>
    <li><%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item'%></li>
  </ul>
</div>
<% else %>
 <%= link_to 'Sign In', new_user_session_path, class: 'link-secondary '%> &nbsp;&nbsp;
 <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-sm btn-outline-secondary'%>
 <% end %>

app/views/layouts/_footer.html.erb
<footer class="py-5 text-center text-body-secondary bg-body-tertiary">
  <p>Blog template built for Ruby</p>
  <%# <p class="mb-0">
    <a href="#">Back to top</a>
  </p> %>
</footer>

app/views/layouts/_navbar.html.erb
<header class="border-bottom lh-1 py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <%= link_to 'Categories', categories_path, class: 'link-secondary'%>
        <%# <a class="link-secondary" href="#">Subscribe</a> %>
      </div>
      <div class="col-4 text-center">
        <h1><%= link_to 'Mavis Djohanna', root_path, class: 'blog-header-logo text-body-emphasis text-decoration-none'%></h1>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
              <%= render  'layouts/account_links' %>

      </div>
    </div>
  </header>
  <%= yield :category_filter %>
</div>

app/views/layouts/_notice.html.erb
<% if notice.present? %>
<div class = "alert alert-success" role= "alert">
    <%= notice %>
</div>
<% end %>

<% if alert.present? %>
<div class = "alert alert-danger" role= "alert">
    <%= alert %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# Link para fazer o dropdown funciona %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

    
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container">
      <%= render  'layouts/navbar' %>
      <%= render 'layouts/notice'%>
    <%= yield %>
    </main>
      <%= render  'layouts/footer' %>
  </body>
</html>